### ISSUE TITLE
Cann't build on jupyter lab 2.1.2 and OS windows 10

### ISSUE THREAD

**Issue by PatoFeliz** [PhE/jupyterlab_graphviz#11]
I got the following build error log:

```
[LabBuildApp] Building in C:\Users\user\Anaconda3\share\jupyter\lab
[LabBuildApp] Node v10.15.3

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node C:\Users\user\Anaconda3\lib\site-packages\jupyterlab\staging\yarn.js install --non-interactive
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.84s.

[LabBuildApp] > node C:\Users\user\Anaconda3\lib\site-packages\jupyterlab\staging\yarn.js yarn-deduplicate -s fewer --fail
[LabBuildApp] yarn run v1.21.1
$ C:\Users\user\Anaconda3\share\jupyter\lab\staging\node_modules\.bin\yarn-deduplicate -s fewer --fail
Done in 1.06s.

[LabBuildApp] > node C:\Users\user\Anaconda3\lib\site-packages\jupyterlab\staging\yarn.js run build:prod:minimize
[LabBuildApp] yarn run v1.21.1
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
C:\Users\user\Anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\cli.js:93
				throw err;
				^

Error: Cannot find module '@deathbeds\jupyterlab_graphviz\package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.resolve (C:\Users\user\Anaconda3\share\jupyter\lab\staging\node_modules\v8-compile-cache\v8-compile-cache.js:166:23)
    at packageNames.forEach.name (C:\Users\user\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\buildutils\lib\build.js:39:45)
    at Array.forEach (<anonymous>)
    at Object.ensureAssets (C:\Users\user\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\buildutils\lib\build.js:38:22)
    at Object.<anonymous> (C:\Users\user\Anaconda3\share\jupyter\lab\staging\webpack.config.js:33:25)
    at Module._compile (C:\Users\user\Anaconda3\share\jupyter\lab\staging\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (C:\Users\user\Anaconda3\share\jupyter\lab\staging\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\Users\user\Anaconda3\share\jupyter\lab\staging\webpack.prod.minimize.config.js:4:14)
    at Module._compile (C:\Users\user\Anaconda3\share\jupyter\lab\staging\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (C:\Users\user\Anaconda3\share\jupyter\lab\staging\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (C:\Users\user\Anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\utils\convert-argv.js:114:13)
    at requireConfig (C:\Users\user\Anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\utils\convert-argv.js:116:6)
    at C:\Users\user\Anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\user\Anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\utils\convert-argv.js:121:15)
    at yargs.parse (C:\Users\user\Anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\cli.js:71:45)
    at Object.parse (C:\Users\user\Anaconda3\share\jupyter\lab\staging\node_modules\yargs\yargs.js:567:18)
    at C:\Users\user\Anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (C:\Users\user\Anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\cli.js:366:3)
child_process.js:637
    throw err;
    ^

Error: Command failed: C:\Users\user\Anaconda3\share\jupyter\lab\staging\node_modules\.bin\webpack.CMD --config webpack.prod.minimize.config.js
    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:13)
    at Object.<anonymous> (C:\Users\user\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\buildutils\lib\ensure-max-old-space.js:38:17)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "C:\Users\user\Anaconda3\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "C:\Users\user\Anaconda3\lib\site-packages\jupyterlab\labapp.py", line 138, in start
    raise e

[LabBuildApp]   File "C:\Users\user\Anaconda3\lib\site-packages\jupyterlab\labapp.py", line 135, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "C:\Users\user\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 460, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "C:\Users\user\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 661, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab
```
